#!/bin/sh

# 开启 2.4G 和 5G 无线射频
uci -q batch <<EOF
set wireless.@wifi-device[0].disabled='0'
set wireless.@wifi-device[1].disabled='0'
set wireless.@wifi-iface[0].disabled='0'
set wireless.@wifi-iface[1].disabled='0'
commit wireless
EOF

exit 0
